# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        mongodb-version: ['6.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: MongoDB in GitHub Actions 
      uses: supercharge/mongodb-github-action@v1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Start MySQL
      env:
        DB_HOST: 127.0.0.1 # maybe use localhost
        DB_NAME: expensesdb
        DB_USER: root
        DB_PASSWORD: root
        DB_PORT: 3306
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
            
          
